# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_by_parent', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('xindex', models.IntegerField()),
                ('yindex', models.IntegerField()),
                ('alert', models.CharField(blank=True, default='', max_length=63)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
