# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancard',
            name='xindex',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kanbancard',
            name='yindex',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
