# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20160510_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbancard',
            options={'permissions': (('view_service', 'View service'),)},
        ),
    ]
