# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendr', '0002_auto_20151029_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'0', b'ToDo'), (b'1', b'Ready'), (b'2', b'In_Progress'), (b'3', b'Done')], default=0, max_length=2),
        ),
    ]
