# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0026_auto_20151204_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[(b'0', b'On_Hold'), (b'1', b'Pending_Assignment'), (b'2', b'Active'), (b'3', b'Overdue'), (b'4', b'Completed')], default=1, max_length=2),
        ),
    ]
