# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0027_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(default=b'Payment', help_text=b'Payment Description.'),
        ),
    ]
