# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0027_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
