# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0028_payment_description'),
        ('gallant', '0028_service_views'),
    ]

    operations = [
    ]
