# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0028_service_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
