# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0029_merge'),
        ('gallant', '0029_service_index'),
    ]

    operations = [
    ]
