# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0031_gallantuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.CharField(blank=True, choices=[(b'0', b'Search'), (b'1', b'Paid_Advertisement'), (b'2', b'Social_Media'), (b'3', b'Client'), (b'4', b'Networking'), (b'5', b'Word_Of_Mouth'), (b'6', b'Other')], max_length=3),
        ),
    ]
