# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0032_auto_20160408_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='size',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[(b'0', b'Pre_Quote'), (b'1', b'Quoted'), (b'2', b'Project_Underway'), (b'3', b'Pending_Payment'), (b'4', b'Closed'), (b'10', b'User_Status')], max_length=2),
        ),
    ]
