# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0033_auto_20160427_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alert',
            field=models.CharField(blank=True, default=b'', max_length=63),
        ),
    ]
