# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0034_client_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[(b'0', b'Potential'), (b'1', b'Quoted'), (b'2', b'Project_Underway'), (b'3', b'Pending_Payment'), (b'4', b'Closed'), (b'10', b'User_Potential'), (b'11', b'User_Quoted'), (b'12', b'User_Project_Underway'), (b'13', b'User_Pending_Payment'), (b'14', b'User_Closed')], max_length=2),
        ),
    ]
