# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0036_auto_20160428_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'permissions': (('view_contact_info', 'View contact info'),)},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='deleted_by_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
