# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 01:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0037_auto_20160509_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallantuser',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='gallantuser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gallantuser',
            name='address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gallantuser',
            name='city',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='gallantuser',
            name='country',
            field=django_countries.fields.CountryField(default=b'US', max_length=2),
        ),
        migrations.AddField(
            model_name='gallantuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+99 (999) 999-9999'. Up to 16 digits allowed.", regex=b'^\\+?\\d{0,3} ?(\\(\\d{1,3}\\))?[\\- \\d]+$')]),
        ),
        migrations.AddField(
            model_name='gallantuser',
            name='state',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='gallantuser',
            name='zip',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message=b"Zipcode must be entered in the format: '12345-1234' (first five digits required).", regex=b'^\\d{5}(?:[-\\s]\\d{4})?$')]),
        ),
    ]
