# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
        ('gallant', '0038_auto_20160509_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='alert',
        ),
        migrations.AddField(
            model_name='client',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.KanbanCard'),
        ),
        migrations.AddField(
            model_name='service',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.KanbanCard'),
        ),
    ]
