# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 16:24
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0039_auto_20160510_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallantuser',
            name='settings',
            field=jsonfield.fields.JSONField(default={}, max_length=511),
        ),
    ]
