# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0040_gallantuser_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallant.Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='gallant.Service'),
        ),
    ]
