# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0041_auto_20160603_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency=b'USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[(b'0', b'Branding'), (b'1', b'Design'), (b'2', b'Architecture'), (b'3', b'Advertising'), (b'4', b'Production'), (b'5', b'Illustration'), (b'6', b'Industrial_Design'), (b'7', b'Fashion_Design'), (b'8', b'Interior_Design')], max_length=2, null=True),
        ),
    ]
