# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallant', '0042_auto_20160603_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
