#!/bin/bash
 
NAME="gallant"                                    # Name of the application
DJANGODIR=/webapps/gallant/                       # Django project directory
SOCKFILE=/webapps/gallant/gunicorn.sock           # we will communicte using this unix socket
USER=gallant                                      # the user to run as
GROUP=gallant                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=gallant.settings.prod_ec2  # which settings file should Django use
DJANGO_WSGI_MODULE=gallant.wsgi                   # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-file=$RUNDIR/logs/gunicorn.log
