"""
Django settings for gallant project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from django.contrib import messages

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '200e^rny&-)38ixcu-k^ivy)o05f=+90utc3!drrny@^0o)n92'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TESTING = 'test' in sys.argv

ALLOWED_HOSTS = []

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

# Application definition

INSTALLED_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',

    'allauth',
    'allauth.account',
    'bootstrapform',
    'custom_user',
    'selenium',
    'django_nose',
    'guardian',
    'django_countries',
    'django_extensions',
    'localflavor',
    'analytical',
    'breadcrumbs',
    'djng',
    'rest_framework',
    'djmoney_rates',

    'gallant',
    'briefs',
    'quotes',
    'calendr',
    'kanban',

    'market_analysis',
    'experiments',
    'django.contrib.humanize',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'breadcrumbs.middleware.BreadcrumbsMiddleware',
    'experiments.middleware.ExperimentsRetentionMiddleware',
)

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)

ROOT_URLCONF = 'gallant.urls'
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
APPEND_SLASH = False

CLICKY_SITE_ID = '100867941'
CRAZY_EGG_ACCOUNT_NUMBER = '00379063'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'gallant.utils.site_processor',
                'gallant.utils.debug_processor',
            ],
        },
    },
]

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

WSGI_APPLICATION = 'gallant.wsgi.application'

IGNORED_WARNINGS = {
    'RemovedInDjango19Warning: django.utils.importlib',
    'RemovedInDjango110Warning'
}


def filter_warnings(record):
    for ignored in IGNORED_WARNINGS:
        if ignored in record.args[0]:
            return False
    return True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'logfile': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + "/django.log",
            'maxBytes': 5000000,
            'backupCount': 2,
        },
    },
    'filters': {
        'ignored_warnings': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': filter_warnings,
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }

    },
    'loggers': {
        'py.warnings': {
            'handlers': ['console', ],
            'filters': ['ignored_warnings', ],
        },
        # uncomment to log DB queries
        #'django.db.backends': {
        #    'level': 'DEBUG',
        #    'handlers': ['logfile'],
        #}
    },
}
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
    os.path.join(BASE_DIR, 'build'),
)

# allauth disable usernames, use email instead
AUTH_USER_MODEL = 'gallant.GallantUser'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ANONYMOUS_USER_ID = -1

# Disable allauth signup for now
ACCOUNT_ADAPTER = 'gallant.utils.NoNewUsersAccountAdapter'


BREADCRUMBS_AUTO_HOME=True

DJANGO_MONEY_RATES = {
    'DEFAULT_BACKEND': 'djmoney_rates.backends.OpenExchangeBackend',
    'OPENEXCHANGE_URL': 'http://openexchangerates.org/api/latest.json',
    'OPENEXCHANGE_APP_ID': '5b3c1669f5484c17bee817b8ff4c893d',
    'OPENEXCHANGE_BASE_CURRENCY': 'USD',
}


# EXPERIMENTS

# Settings
EXPERIMENTS_GOALS = (
    'page_goal',
)

EXPERIMENTS_AUTO_CREATE = True

EXPERIMENTS_VERIFY_HUMAN = True #Careful with this setting, if it is toggled then participant counters will not increment accordingly

# Redis Settings
EXPERIMENTS_REDIS_HOST = 'localhost'
EXPERIMENTS_REDIS_PORT = 6379
EXPERIMENTS_REDIS_DB = 0