# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallant.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallant', '0027_service_status'),
        ('quotes', '0018_auto_20151204_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_by_parent', models.BooleanField(default=False)),
                ('name', models.CharField(default=b'section', max_length=256)),
                ('index', models.IntegerField(default=0)),
                ('title', gallant.fields.ULCharField(blank=True)),
                ('text', gallant.fields.ULTextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_text', 'View text'),),
            },
        ),
        migrations.RemoveField(
            model_name='quote',
            name='service_sections',
        ),
        migrations.RemoveField(
            model_name='section',
            name='index',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='quote',
            name='services',
            field=models.ManyToManyField(blank=True, to='gallant.Service'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sections',
            field=models.ManyToManyField(blank=True, to='quotes.Text'),
        ),
    ]
