# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_auto_20151213_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='section',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='section_ptr',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='service',
        ),
        migrations.RemoveField(
            model_name='textsection',
            name='section_ptr',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
        migrations.DeleteModel(
            name='TextSection',
        ),
    ]
