# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_auto_20151213_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Section',
        ),
    ]
