# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_auto_20151213_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'permissions': (('view_section', 'View section'),)},
        ),
    ]
