# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_auto_20160128_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
