# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_auto_20160129_1144'),
        ('quotes', '0022_auto_20160126_1610'),
    ]

    operations = [
    ]
