# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_auto_20160129_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='session_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
