# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0024_merge'),
        ('quotes', '0024_quote_session_duration'),
    ]

    operations = [
    ]
