# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20160510_1308'),
        ('quotes', '0025_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.KanbanCard'),
        ),
    ]
