# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 04:31
from __future__ import unicode_literals

from django.db import migrations


def delete_sections(apps, schema_editor):
    Sections = apps.get_model("quotes", "Section")

    Sections.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0027_auto_20160511_1451'),
    ]

    operations = [
        migrations.RunPython(delete_sections)
    ]
